name: A workflow for my Hello World file
on: push
jobs:
    build:
      name: Hello world action
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: ./action-a
          with:
            MY_NAME: "Mona"
            version: 2
            jobs:
              static-analysis:
                docker:
                  - image: circleci/openjdk:latest
                steps:
                  - checkout
                  - restore_cache:
                      keys: 
                        - pmd-v6.0.1
                  - run:
                      name: Install PMD
                      command: |
                          if [ ! -d pmd-bin-6.0.1 ]; then
                              curl -L "https://github.com/pmd/pmd/releases/download/pmd_releases/6.0.1/pmd-bin-6.0.1.zip" -o pmd-bin-6.0.1.zip
                              unzip pmd-bin-6.0.1.zip
                              rm pmd-bin-6.0.1.zip
                          fi
                  - save_cache:
                      key: pmd-v6.0.1
                      paths: 
                          - pmd-bin-6.0.1
                  - run: 
                      name: Run Static Analysis
                      command: |
                          pmd-bin-6.0.1/bin/run.sh pmd -d . -R $RULESET -f text -l apex -r static-analysis.txt 
                  - store_artifacts:
                      path: static-analysis.txt
              build-enterprise:
                 <<: *jobdef
                 environment:
                    SCRATCH_DEF: project-scratch-def.json
              build-developer: 
                 <<: *jobdef
                 environment:
                    SCRATCH_DEF: developer.json
            workflows:
              version: 2
              test_and_static:
                jobs:
                  - build-enterprise
                  - build-developer
                  - static-analysis